# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email_sended', models.BooleanField(default=True)),
                ('random_Text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai', models.TimeField()),
                ('selesai', models.TimeField()),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=25)),
                ('ruangan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_matkul', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=250, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('npm', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jadwal',
            name='matkul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.Matkul'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='matkul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.Matkul'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='referensi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.Referensi'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.Jadwal'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='referensi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.Referensi'),
        ),
    ]
