# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-17 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0004_auto_20180417_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absensi',
            old_name='random_Text',
            new_name='random_text',
        ),
    ]
