# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0005_auto_20180417_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.Jadwal')),
                ('referensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.Referensi')),
            ],
        ),
    ]
