# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPM', models.CharField(max_length=10)),
                ('Timestamp', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Referensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC_Address', models.CharField(max_length=250)),
                ('Nama', models.CharField(max_length=500)),
                ('NPM', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='absensi',
            name='Kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Referensi'),
        ),
    ]
