# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180315_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='Kelas',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='NPM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Referensi'),
        ),
    ]
