# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-17 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_referensi_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='Email_Confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
