# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-20 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20180319_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absensi',
            old_name='Biodata',
            new_name='NPM',
        ),
    ]
