# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20180320_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='Email_Sended',
            field=models.BooleanField(default=False),
        ),
    ]
