# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20180320_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mulai', models.DateTimeField(auto_now_add=True)),
                ('Selesai', models.DateTimeField(auto_now_add=True)),
                ('Ruangan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='referensi',
            name='Mata_Kuliah',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='Email_Sended',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='Matkul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Matkul'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Referensi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Referensi'),
        ),
    ]
