# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20180409_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absensi',
            old_name='NPM',
            new_name='Referensi',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='Kelas',
        ),
        migrations.RemoveField(
            model_name='matkul',
            name='Enrollment',
        ),
        migrations.AddField(
            model_name='absensi',
            name='Jadwal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.Jadwal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Matkul',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.Matkul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matkul',
            name='Nama_Matkul',
            field=models.CharField(default='', max_length=255),
        ),
    ]
