# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20180409_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referensi',
            name='Mata_Kuliah',
        ),
    ]
