# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_referensi_mata_kuliah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='Mulai',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='Selesai',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='Nama_Matkul',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='referensi',
            name='NPM',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
