# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20180409_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='Hari',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='Mulai',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='Selesai',
            field=models.TimeField(),
        ),
    ]
